#                               #                                                                                                         #
#                               #                                                                                                         #
#                               #                                                                                                         #
#                               ###########################################################################################################
#                               #                                                                                                         #
#                               #   ░█████╗░░█████╗░███╗░░██╗███████╗██╗░██████╗░██╗░░░██╗██████╗░░█████╗░████████╗██╗░█████╗░███╗░░██╗   #
#                               #   ██╔══██╗██╔══██╗████╗░██║██╔════╝██║██╔════╝░██║░░░██║██╔══██╗██╔══██╗╚══██╔══╝██║██╔══██╗████╗░██║   #
#                               #   ██║░░╚═╝██║░░██║██╔██╗██║█████╗░░██║██║░░██╗░██║░░░██║██████╔╝███████║░░░██║░░░██║██║░░██║██╔██╗██║   #
#                               #   ██║░░██╗██║░░██║██║╚████║██╔══╝░░██║██║░░╚██╗██║░░░██║██╔══██╗██╔══██║░░░██║░░░██║██║░░██║██║╚████║   #
#                               #   ╚█████╔╝╚█████╔╝██║░╚███║██║░░░░░██║╚██████╔╝╚██████╔╝██║░░██║██║░░██║░░░██║░░░██║╚█████╔╝██║░╚███║   #
#                               #   ░╚════╝░░╚════╝░╚═╝░░╚══╝╚═╝░░░░░╚═╝░╚═════╝░░╚═════╝░╚═╝░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░╚═╝░╚════╝░╚═╝░░╚══╝   #
#                               #                                                                                                         #
#                               ###########################################################################################################
#
#
#
# Welcome to the configuration EN of the plugin ! You'll find here a guide to configure the plugin !
# Si vous êtes un francophone, une aide de configuration en français est disponible dans le fichier
# "config_fr.yml" dans le dossier ressources.
#
#


# Defines the 3 items of the plugin, the settings are the sames for the three items
Items:
  BasicDebugStick:
    # The material of the object (e.g. : ARROW)
    Material: "BAMBOO"

    # The name of the object.
    Name: "<s:33FFBB>&lBASIC DEBUG STICK<e:33FFBB>"

    # His lore, his description. Each element of the list is a line of the lore.
    Lore: #{durability}
      - ""
      - "&e&lRIGHT-CLICK"
      - " &7&oto edit rotations properties"
      - ""
      - "&a&lLEFT-CLICK"
      - " &7&oto edit reverses properties"
      - ""
      - "&c&lSHIFT + RIGHT-CLICK"
      - " &7&oto edit specials properties"
      - ""
      - "&9&lSHIFT + LEFT-CLICK"
      - " &7&oto edit creatives properties"
      - ""
      - "&aUses left : &e{durability}"

    # Enchant(s) of the items, each element represent an enchant. You don't have to add the  "minecraft:" before
    # the name of to enchant. It's not necessary for an item to have an enchant.
    Enchants:

    # Flags of the item to enable (true) or disable (false)
    # Hide enchants
    HideEnchants: true

    # Hide attributes (example : +2 attack damage)
    HideAttributes: true

    # Hide potion effect
    HidePotionEffets: true

    # Hide if the item is dyed or not
    HideDye: true

    # Hide if the item can be placed only on some blocks
    HidePlacedOn: true

    # Give the flag "unbreakable" to the item (this field don't change the properties of the item, it's juste cosmetic)
    IsUnbreakable: false

  InfinityDebugStick:
    Material: "DEAD_BUSH"
    Name: "<s:E60000>&lRACINE DE<e:FFD919><s:FFD919>&l DÉBOGAGE<e:E60000>"
    Lore:
      - ""
      - "&e&lRIGHT-CLICK"
      - " &7&oto edit rotations properties"
      - ""
      - "&a&lLEFT-CLICK"
      - " &7&oto edit reverses properties"
      - ""
      - "&c&lSHIFT + RIGHT-CLICK"
      - " &7&oto edit specials properties"
      - ""
      - "&9&lSHIFT + LEFT-CLICK"
      - " &7&oto edit creatives properties"
      - ""
      - "&aUse left : &e∞"


    Enchants:
      - "unbreaking"
    HideEnchants: true
    HideAttributes: true
    HidePotionEffets: true
    HideDye: true
    IsUnbreakable: true
    HideUnbreakable: false
    HidePlacedOn: true

  Inspector:
    Material: "GOLD_INGOT"
    Name: "<s:FF8C19>&lINSPECTOR<e:FF8C19>"
    Lore:
      - ""
      - "&a&lRIGHT-CLICK &7&oto have implementations"
      - "&c&lLEFT-CLICK &7&oto have values of properties"
    Enchants:
      - "unbreaking"

    HideEnchants: false
    HideAttributes: true
    HidePotionEffets: true
    HideDye: true
    IsUnbreakable: true
    HideUnbreakable: false
    HidePlacedOn: true

Settings:
  # The damage that the durability will take when the debug stick modify this property.
  # (see in the file "properties_en.yml" in the folder ressources, the definition of each property)
  Durability:
    ORIENTABLE: 1
    DIRECTIONAL: 1
    ROTATABLE: 1
    SLAB: 1
    BISECTED: 1
    SHAPE_STAIRS: 1
    SHAPE_RAIL: 1
    PERSISTENT: 3
    MULTIPLEFACING: 1
    LIGHTABLE: 5
    REDSTONEWIRE: 2
    WATERLOGGED: 3
    POWERABLE: 10
    AGEABLE: 20
    SAPLING: 10
    BEEHIVE: 5
    WALL: 1
    SNOWABLE: 3
    DISTANCE: 1
    LAYERS: 1

  BlackList:
    # List of materials that can't be modified
    Material:
      - "CHEST"

    # List of worlds name where the debug stick cannot be used
    World:
      - "world_the_end"


  # Write in the console when a player changes a property
  logConsole: false

  # Write in apart file when a player changes a property
  logFile: false

  # Warn the player when his debug stick will break
  # The configuration of the message is in the "messages.yml" file at "OnUse" -> "WarnBreakMessage"
  WarnPlayerWhenBreaking:
    Enable: true

    # Send the message one time (true) or each time the player will use the debug stick and his durability
    # is below or equal to the durability settled (false)
    SendOnce: false
    Durability: 5


# Here you can create recipes for the debug stick of the plugin
# To create a recipe, you have to create a new field in the recipes section and name
# it like you want (different name per recipe).
# In this new field,  you have to have 2 children fields : 'durability' -> the durability of the debug stick (use -1 for
# the infinity debug stick) and the 'craft' field composed of number representing the slot in a crafting table like this :
#
#   / / / / / / /
#   / 1 / 2 / 3 /    / / / / / / / / /
#   / 4 / 5 / 6 / -> /the debug stick/
#   / 7 / 8 / 9 /    / / / / / / / / /
#   / / / / / / /
#
# You must not use all slot but each slot that you want to use, represent a material
# here is for you 2 examples of recipes :
recipes:
#  first:
#    durability: 10
#    craft:
#      2: "BAMBOO"
#      5: "BAMBOO"
#      8: "BAMBOO"
#  infinity:
#    durability: -1
#    craft:
#      1: "DIAMOND"
#      3: "EMERALD"