name: ProtectedDebugStick
author: Machigan
version: 1.1.0
main: be.machigan.protecteddebugstick.ProtectedDebugStick
database: false

softdepend: [PlaceholderAPI]

api-version: 1.18

commands:
  pds:
    description: Allows player to give a protected debug stick or reload the plugin
    usage: Somes arguments are not existing
    aliases:
      - protected-debug-stick



permissions:
  pds.*:
    description: Allows player to have all permissions of the plugin
    default: false
    children:
      pds.command.*: true
      pds.property.*: true
      pds.item.*: true


  # Command permissions :
  pds.command.*:
    description: Allows player to use all the argument of the command /PDS
    default: op
    children:
      pds.command.use: true
      pds.command.give: true
      pds.command.reload-config: true
      pds.command.load: true
  # Children permissions of command :
  pds.command.use:
    description: Allows player to use the command /PDS
    default: op
  pds.command.give:
    description: Allows player to use the command /PDS give
    default: op
  pds.command.reload-config:
    description: Allows player to use the command /PDS reload-config
    default: op
  pds.command.load:
    description: Allows player to load a file from resources folder
    default: op


  # Item permissions :
  pds.item.*:
    description: Allows player to use all items
    default: false
    children:
      pds.item.basic.*: true
      pds.item.infinite.*: true
      pds.item.inspector.*: true
  # Children permissions of item :

  # Basic debugstick permissions :
  pds.item.basic.*:
    description: Allows player to use all fonctionnalities of the basic debug stick
    children:
      pds.item.basic.edit: true
      pds.item.basic.see: true
  # Children permissions of basic debugstick :
  pds.item.basic.edit:
    description: Allows player to edit the property with the basic
    default: true
  pds.item.basic.see:
    description: Allows player to see all editables properties of a block (and it cost) with the basic
    default: true

  # Infinite debugstick permissions :
  pds.item.infinite.*:
    description: Allows player to use all fonctionnalities of the infinite debug stick
    default: false
    children:
      pds.item.infinite.edit: true
      pds.item.infinite.see: true
  # Children permissions of infinite debugstick :
  pds.item.infinite.edit:
    description: Allows player to edit the property with the infinite
    default: false
  pds.item.infinite.see:
    description: Allows player to see all editables properties of a block (and it cost) with the infinite
    default: false

  # Inspector permissions :
  pds.item.inspector.*:
    description: Allows player to use all fonctionnalities of the inspector
    default: false
    children:
      pds.item.inspector.implementation: true
      pds.item.inspector.properties: true
  # Children permissions of inspector :
  pds.item.inspector.implementation:
    description: Allows player to see all implementations of a block with the inspector
    default: false
  pds.item.inspector.properties:
    description: Allows player to see all properties and it values of a block with the inspector
    default: false


  # Bypass permissions :
  pds.bypass.*:
    description: Allows player to bypass all restrictions of the plugin
    default: op
    children:
      pds.bypass.blacklist.*: true
      pds.bypass.plugin-block: true
  # Children permissions of bypass :
  pds.bypass.plugin-block:
    description: Allows player to bypass the others plugin protection
    default: op

  # Permissions of blacklist
  pds.bypass.blacklist.*:
    description: Allows player to bypass all blacklist
    default: op
    children:
      pds.bypass.blacklist.material: true
      pds.bypass.blacklist.world: true
  # Children permissions of blacklist :
  pds.bypass.blacklist.material:
    description: Allows player to bypass the material blacklist
    default: op
  pds.bypass.blacklist.world:
    description: Allows player to bypass the world blacklist
    default: op


  # Property permissions :
  pds.property.*:
    description: Allows player to edit all the properties
    default: false
    children:
      pds.property.orientable: true
      pds.property.directional: true
      pds.property.rotatable: true
      pds.property.slab: true
      pds.property.bisected: true
      pds.property.shape-stairs: true
      pds.property.shape-rail: true
      pds.property.persistent: true
      pds.property.multiple-facing: true
      pds.property.lightable: true
      pds.property.redstone-wire: true
      pds.property.water-logged: true
      pds.property.powerable: true
      pds.property.ageable: true
      pds.property.sapling: true
      pds.property.beehive: true
      pds.property.wall: true
      pds.property.snowable: true
      pds.property.distance: true
      pds.property.layers: true
  # Children permissions of property :
  pds.property.orientable:
    description: Allows player to edit the property orientable
    default: true
  pds.property.directional:
    description: Allows player to edit the property directional
    default: true
  pds.property.rotatable:
    description: Allows player to edit the property rotatable
    default: true
  pds.property.slab:
    description: Allows player to edit the property slab
    default: true
  pds.property.bisected:
    description: Allows player to edit the property bisected
    default: true
  pds.property.shape-stairs:
    description: Allows player to edit the property shape of stairs
    default: true
  pds.property.shape-rail:
    description: Allows player to edit the property shape of rail
    default: true
  pds.property.persistent:
    description: Allows player to edit the property persistent
    default: true
  pds.property.multiple-facing:
    description: Allows player to edit the property multiple facing
    default: true
  pds.property.lightable:
    description: Allows player to edit the property lightable
    default: true
  pds.property.redstone-wire:
    description: Allows player to edit the property redstone wire
    default: true
  pds.property.water-logged:
    description: Allows player to edit the property water logged
    default: false
  pds.property.powerable:
    description: Allows player to edit the property powerable
    default: false
  pds.property.ageable:
    description: Allows player to edit the property ageable
    default: false
  pds.property.sapling:
    description: Allows player to edit the property sapling
    default: false
  pds.property.beehive:
    description: Allows player to edit the property beehive
    default: false
  pds.property.wall:
    description: Allows player to edit the property wall
    default: true
  pds.property.snowable:
    description: Allows player to edit the property snowable
    default: true
  pds.property.distance:
    description: Allows player to edit the property distance
    default: true
  pds.property.layers:
    description: Allows player to edit the property layers
    default: false
